### ISSUE TITLE
Fatal error when cart contains subscription

### ISSUE THREAD

**Issue by bporcelli** [bporcelli/simplesalestax#26]
A customer reported that a fatal error is occurring at checkout when the cart contains a subscription. The error message is copied below.

```
2019-07-19T17:01:50+00:00 CRITICAL Uncaught Error: Call to undefined method WC_Subscriptions_Cart::cart_contains_free_trial() in /wp-content/plugins/simplesalestax/includes/class-sst-subscriptions.php:221
Stack trace:
#0 /wp-includes/class-wp-hook.php(286): SST_Subscriptions->add_package_for_no_ship_subs(Array, Object(SST_Cart_Proxy))
#1 /wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array)
#2 /wp-content/plugins/simplesalestax/includes/frontend/class-sst-checkout.php(279): apply_filters('wootax_cart_pac...', Array, Object(SST_Cart_Proxy))
#3 /wp-content/plugins/simplesalestax/includes/abstracts/class-sst-abstract-cart.php(110): SST_Checkout->create_packages()
#4 /wp-content/plugins/simplesalestax/includes/abstracts/class-sst-abstract-cart.php(62): SST_Abstract_Cart->do_lookup()
#5 /home3/northxp1/pub in /wp-content/plugins/simplesalestax/includes/class-sst-subscriptions.php on line 221
```

**Comment by bporcelli** [comment]
I'm unable to reproduce this issue with WooCommerce 3.6.5 and WooCommerce Subscriptions 2.5.7. My guess is that the customer is running an ancient version of Subscriptions. Will update when full WooCommerce Status report is received.

**Comment by bporcelli** [comment]
It turns out that this customer is using an incompatible Subscriptions plugin, namely Subscriptions for WooCommerce by WebToffee. We need to add some checks to ensure that the Subscriptions integration is only loaded when the supported WooCommerce Subscriptions plugin is installed.
